<a href="https://colab.research.google.com/github/Lu1sV1rus/Estocasticos/blob/main/Estocasticos3_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

El Sr. y la Sra. H han planeado celebrar su 25º aniversario de bodas en Honeymooners' Paradise, un popular complejo turístico en la ciudad de Centerville. Contando hoy como el primer día, se supone que estarán allí el séptimo y el octavo día. Están pensando en comprar un seguro de viaje que les reembolsará el costo total del paquete vacacional de \$2500 si llueve ambos días, y no se les reembolsará nada en caso contrario. El seguro cuesta \$200. Supongamos que el clima en la ciudad de Centerville cambia según el modelo de CMTD de tres estados (soleado, nublado y lluvioso) visto en clase. Suponiendo que hoy hace sol en la ciudad de Centerville, ¿deberían el Sr. y la Sra. H comprar el seguro

In [20]:
import numpy as np
p=np.array([[0.7,0.2,0.1],  #sol
            [0.3,0.5,0.2],  #nublado
            [0.2,0.4,0.4]]) #lluvioso
print(p)

# Dia 1 = [1, 0, 0]
v1 = np.array([1, 0, 0]) # Hoy sol

[[0.7 0.2 0.1]
 [0.3 0.5 0.2]
 [0.2 0.4 0.4]]


In [21]:
# Dia 7
p7 = v1 @ np.linalg.matrix_power(p, 6)
print("Dia 7",p7)

# Probabilidad de lluvia el dia 7
r7 = p7[2]
print(f"Probabilidad de lluvia dia 7: {r7}")

# lluvia dia 7 Y el día 8
# P(R7 y R8) = P(R7) * P(R8|R7)
r78 = r7 * p[2, 2]
print(f"Probabilidad de lluvia 7 y 8: {r78}")

# Valor Esperado del seguro
esp = r78 * 2500
print(f"Valor esperado del reembolso: ${esp}, Costo del seguro: $200")
print(f"Ganancia: ${esp-200}")

Dia 7 [0.471945 0.338164 0.189891]
Probabilidad de lluvia dia 7: 0.18989099999999998
Probabilidad de lluvia 7 y 8: 0.0759564
Valor esperado del reembolso: $189.891, Costo del seguro: $200
Ganancia: $-10.109000000000009
